language: ruby

rvm:
- 2.0

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

anstall: gem install jekyll
script: jekyll doctor && jekyll clean && jekyll build


